# Generated by Django 3.0.8 on 2021-01-05 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parroquias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parroquia',
            name='administrador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador'),
        ),
        migrations.AddField(
            model_name='imagenesparroquia',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parroquias.Parroquia', verbose_name='Parroquia'),
        ),
    ]
