# Generated by Django 3.0.8 on 2021-01-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parroquias', '0002_auto_20210105_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='nombre_parr',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la parroquia'),
        ),
    ]
