# Generated by Django 3.0.8 on 2020-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parroquias', '0002_auto_20201128_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='nombre_parr',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de la parroquia'),
        ),
    ]
