# Generated by Django 3.0.8 on 2021-01-02 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parroquias', '0004_auto_20201211_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='administrador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador'),
        ),
    ]
