# Generated by Django 3.0.8 on 2020-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atractivos_naturales', '0002_auto_20201128_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atractivonatural',
            name='nombre_an',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del atractivo Natural'),
        ),
        migrations.AlterField(
            model_name='tipoan',
            name='nombre_tipo_an',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
