# Generated by Django 3.0.8 on 2020-12-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atractivos_naturales', '0004_auto_20201211_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atractivonatural',
            options={'ordering': ['nombre'], 'verbose_name': 'AtractivoNatural', 'verbose_name_plural': 'Atractivos Naturales'},
        ),
        migrations.RenameField(
            model_name='atractivonatural',
            old_name='direccion_an',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='atractivonatural',
            old_name='latitud_an',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='atractivonatural',
            old_name='longitud_an',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='atractivonatural',
            old_name='nombre_an',
            new_name='nombre',
        ),
    ]
