# Generated by Django 3.0.8 on 2021-01-05 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parroquias', '0001_initial'),
        ('atractivos_culturales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atractivocultural',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parroquias.Parroquia', verbose_name='Parroquia'),
        ),
        migrations.AddField(
            model_name='atractivocultural',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atractivos_culturales.TipoAC', verbose_name='Tipo de atractivo'),
        ),
    ]
