# Generated by Django 3.0.8 on 2020-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atractivos_culturales', '0003_auto_20201128_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atractivocultural',
            name='direccion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atractivocultural',
            name='latitud',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atractivocultural',
            name='longitud',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
