# Generated by Django 3.0.8 on 2021-01-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadministracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacionturismo',
            options={'ordering': ['titulo'], 'verbose_name': 'InformacionTurismo', 'verbose_name_plural': 'Informacion del sitio'},
        ),
        migrations.AlterField(
            model_name='informacionturismo',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
