# Generated by Django 3.0.8 on 2020-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0002_alojamiento_parroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
