# Generated by Django 3.0.8 on 2020-12-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamiento', '0003_auto_20201128_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='direccion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='latitud',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='longitud',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
