# Generated by Django 3.0.8 on 2020-12-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20201211_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoemp',
            name='descripcion',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Descripcion'),
        ),
    ]
