# Generated by Django 3.0.8 on 2020-12-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20201211_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
