# Generated by Django 3.0.8 on 2020-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotransporte',
            name='nombre_tipo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
