# Generated by Django 3.0.8 on 2020-12-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_auto_20201128_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='tipo_id',
        ),
    ]
